services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-app_db}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./storage/docker/db:/var/lib/postgresql/data
